spring:
  datasource:
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/banking_app
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

build:
  version: 1.2

